// Code generated by gombit new. DO NOT EDIT.

package web

import (
	"embed"
	"io/fs"
)

// Files is the go:embed tree of static/. After gombit new it contains only
// .keep (no index.html), so framework.WithEmbeddedFrontend does not install
// SPA fallback. gombit build --embed copies the Vite production build here.
//
//go:embed all:static
var Files embed.FS

// FS returns the embedded frontend tree rooted at static/.
// If fs.Sub fails, it returns an empty embed.FS rather than Files: the SPA
// lives under static/, so the un-subbed root would miss index.html.
func FS() fs.FS {
	sub, err := fs.Sub(Files, "static")
	if err != nil {
		return embed.FS{}
	}
	return sub
}
