// Code generated by gombit make resource. DO NOT EDIT.
package release

import time "time"

// releaseData is the response body for a Release.
type releaseData struct {
	ID          uint      `json:"id" doc:"ID"`
	CreatedAt   time.Time `json:"created_at" doc:"CreatedAt"`
	UpdatedAt   time.Time `json:"updated_at" doc:"UpdatedAt"`
	Tag         string    `json:"tag" doc:"Tag"`
	Name        string    `json:"name" doc:"Name"`
	Body        string    `json:"body" doc:"Body"`
	Url         string    `json:"url" doc:"Url"`
	PublishedAt string    `json:"published_at" doc:"PublishedAt"`
	Tldr        string    `json:"tldr" doc:"Tldr"`
	TldrStatus  string    `json:"tldr_status" doc:"TldrStatus"`
}

// releaseCreateBody is the request body for creating a Release.
type releaseCreateBody struct {
}

// toReleaseData projects a Release into its response DTO.
func toReleaseData(row Release) releaseData {
	return releaseData{
		ID:          row.Model.ID,
		CreatedAt:   row.Model.CreatedAt,
		UpdatedAt:   row.Model.UpdatedAt,
		Tag:         row.Tag,
		Name:        row.Name,
		Body:        row.Body,
		Url:         row.Url,
		PublishedAt: row.PublishedAt,
		Tldr:        row.Tldr,
		TldrStatus:  row.TldrStatus,
	}
}

// releaseFromCreateBody builds a new Release from a create request.
func releaseFromCreateBody(body releaseCreateBody) Release {
	var row Release
	return row
}
