// Code generated by gombit make resource. DO NOT EDIT.
package release

import (
	"context"
	"net/http"
	"strconv"

	"github.com/danielgtaylor/huma/v2"
	"github.com/gombit-dev/gombit/contract"
	"github.com/gombit-dev/gombit/database"
	"github.com/gombit-dev/gombit/framework"
	"gorm.io/gorm"
)

// ReleaseHooks are the customization points for the generated Release handler.
// The generated handler owns the invariant CRUD sequence and calls these; set
// server-managed columns (tenant, owner, …) in BeforeCreate rather than editing
// generated plumbing.
type ReleaseHooks interface {
	BeforeCreate(ctx context.Context, row *Release, body releaseCreateBody) error
}

// Handler serves Release HTTP operations over GORM. Register wires DB and Hooks.
type Handler struct {
	DB    *gorm.DB
	Hooks ReleaseHooks
}

type listReleasesOutput struct {
	Body contract.DataMeta[[]releaseData, contract.PageMeta]
}

type listReleasesInput struct {
	Page       int    `query:"page" doc:"1-based page"`
	PerPage    int    `query:"per_page" doc:"Page size"`
	Search     string `query:"search" doc:"Search term matched across searchable fields"`
	Ordering   string `query:"ordering" doc:"Field to order by; prefix with - for DESC (allowed: published_at)"`
	TldrStatus string `query:"tldr_status" doc:"Filter by TldrStatus (exact match)"`
}

type getReleaseInput struct {
	ID string `path:"id" doc:"Release identifier"`
}

type getReleaseOutput struct {
	Body contract.Data[releaseData]
}

type createReleaseInput struct {
	Body releaseCreateBody
}

type createReleaseOutput struct {
	Body contract.Data[releaseData]
}

func (h *Handler) list(ctx context.Context, input *listReleasesInput) (*listReleasesOutput, error) {
	page, perPage := contract.ClampPage(input.Page, input.PerPage)
	q := h.DB.WithContext(ctx).Model(&Release{})
	q, err := database.FilterEq(ctx, q, "tldr_status", database.FilterString, input.TldrStatus)
	if err != nil {
		return nil, err
	}
	q = database.Search(q, []string{"tag", "name"}, input.Search)
	var total int64
	if err := q.Session(&gorm.Session{}).Count(&total).Error; err != nil {
		return nil, contract.WithContext(ctx, contract.Internal("list releases"))
	}
	q, err = database.Ordering(ctx, q, input.Ordering, []string{"published_at"}, "id")
	if err != nil {
		return nil, err
	}
	var rows []Release
	if err := q.Offset(contract.PageOffset(page, perPage)).Limit(perPage).Find(&rows).Error; err != nil {
		return nil, contract.WithContext(ctx, contract.Internal("list releases"))
	}
	items := make([]releaseData, 0, len(rows))
	for _, row := range rows {
		items = append(items, toReleaseData(row))
	}
	return &listReleasesOutput{
		Body: contract.DataMeta[[]releaseData, contract.PageMeta]{
			Data: items,
			Meta: &contract.PageMeta{Page: page, PerPage: perPage, Total: total},
		},
	}, nil
}

func (h *Handler) get(ctx context.Context, input *getReleaseInput) (*getReleaseOutput, error) {
	id, err := strconv.ParseUint(input.ID, 10, 64)
	if err != nil {
		return nil, contract.WithContext(ctx, contract.NotFound("release not found"))
	}
	var row Release
	if err := h.DB.WithContext(ctx).First(&row, uint(id)).Error; err != nil {
		return nil, database.MapLoadError(ctx, err, "release not found", "load release")
	}
	return &getReleaseOutput{Body: contract.Data[releaseData]{Data: toReleaseData(row)}}, nil
}

func (h *Handler) create(ctx context.Context, input *createReleaseInput) (*createReleaseOutput, error) {
	if h.Hooks == nil {
		return nil, contract.WithContext(ctx, contract.Internal("create release: Handler.Hooks is not set"))
	}
	row := releaseFromCreateBody(input.Body)
	if err := h.Hooks.BeforeCreate(ctx, &row, input.Body); err != nil {
		return nil, err
	}
	if err := h.DB.WithContext(ctx).Create(&row).Error; err != nil {
		return nil, database.MapPersistError(ctx, err, "resource already exists", "create release")
	}
	return &createReleaseOutput{Body: contract.Data[releaseData]{Data: toReleaseData(row)}}, nil
}

// Register mounts release Huma routes, wiring the human-owned Hooks.
func Register(app *framework.App) {
	h := &Handler{DB: app.DB(), Hooks: Hooks{}}
	prefix := app.Config().API.Prefix
	api := app.API()

	huma.Register(api, huma.Operation{
		OperationID: "list-releases",
		Method:      http.MethodGet,
		Path:        prefix + "/releases",
		Summary:     "List releases",
		Tags:        []string{"Releases"},
	}, h.list)

	huma.Register(api, huma.Operation{
		OperationID: "get-release",
		Method:      http.MethodGet,
		Path:        prefix + "/releases/{id}",
		Summary:     "Get a release",
		Tags:        []string{"Releases"},
	}, h.get)

	huma.Register(api, huma.Operation{
		OperationID: "create-release",
		Method:      http.MethodPost,
		Path:        prefix + "/releases",
		Summary:     "Create a release",
		Tags:        []string{"Releases"},
	}, h.create)

}
