// Code generated by gombit make resource. DO NOT EDIT.
package release

import (
	"context"
	"strconv"

	"github.com/gombit-dev/gombit/contract"
	"github.com/gombit-dev/gombit/database"
	"gorm.io/gorm"
)

// Handler serves release HTTP operations over GORM.
type Handler struct {
	DB *gorm.DB
}

type releaseData struct {
	ID          uint   `json:"id" example:"1" doc:"Release identifier"`
	Tag         string `json:"tag" doc:"Tag"`
	Name        string `json:"name" doc:"Name"`
	Body        string `json:"body" doc:"Body"`
	Url         string `json:"url" doc:"Url"`
	PublishedAt string `json:"published_at" doc:"PublishedAt"`
	Tldr        string `json:"tldr" doc:"Tldr"`
	TldrStatus  string `json:"tldr_status" doc:"TldrStatus"`
}

type listReleasesOutput struct {
	Body contract.DataMeta[[]releaseData, contract.PageMeta]
}

type listReleasesInput struct {
	Page    int `query:"page" doc:"1-based page"`
	PerPage int `query:"per_page" doc:"Page size"`
}

type getReleaseInput struct {
	ID string `path:"id" doc:"Release identifier"`
}

type getReleaseOutput struct {
	Body contract.Data[releaseData]
}

type createReleaseInput struct {
	Body struct {
		Tag         string `json:"tag" minLength:"1" maxLength:"255" doc:"Tag"`
		Name        string `json:"name" maxLength:"255" doc:"Name"`
		Body        string `json:"body" doc:"Body"`
		Url         string `json:"url" maxLength:"255" doc:"Url"`
		PublishedAt string `json:"published_at" maxLength:"255" doc:"PublishedAt"`
		Tldr        string `json:"tldr" doc:"Tldr"`
		TldrStatus  string `json:"tldr_status" maxLength:"255" doc:"TldrStatus"`
	}
}

type createReleaseOutput struct {
	Body contract.Data[releaseData]
}

func (h *Handler) list(ctx context.Context, input *listReleasesInput) (*listReleasesOutput, error) {
	page, perPage := contract.ClampPage(input.Page, input.PerPage)
	q := h.DB.WithContext(ctx).Model(&Release{})
	var total int64
	if err := q.Session(&gorm.Session{}).Count(&total).Error; err != nil {
		return nil, contract.WithContext(ctx, contract.Internal("list releases"))
	}
	var rows []Release
	if err := q.Order("id").Offset(contract.PageOffset(page, perPage)).Limit(perPage).Find(&rows).Error; err != nil {
		return nil, contract.WithContext(ctx, contract.Internal("list releases"))
	}
	items := make([]releaseData, 0, len(rows))
	for _, row := range rows {
		items = append(items, toReleaseData(row))
	}
	return &listReleasesOutput{
		Body: contract.DataMeta[[]releaseData, contract.PageMeta]{
			Data: items,
			Meta: &contract.PageMeta{Page: page, PerPage: perPage, Total: total},
		},
	}, nil
}

func (h *Handler) get(ctx context.Context, input *getReleaseInput) (*getReleaseOutput, error) {
	id, err := strconv.ParseUint(input.ID, 10, 64)
	if err != nil {
		return nil, contract.WithContext(ctx, contract.NotFound("release not found"))
	}
	var row Release
	if err := h.DB.WithContext(ctx).First(&row, uint(id)).Error; err != nil {
		return nil, database.MapLoadError(ctx, err, "release not found", "load release")
	}
	return &getReleaseOutput{
		Body: contract.Data[releaseData]{Data: toReleaseData(row)},
	}, nil
}

func (h *Handler) create(ctx context.Context, input *createReleaseInput) (*createReleaseOutput, error) {
	row := Release{
		Tag:         input.Body.Tag,
		Name:        input.Body.Name,
		Body:        input.Body.Body,
		Url:         input.Body.Url,
		PublishedAt: input.Body.PublishedAt,
		Tldr:        input.Body.Tldr,
		TldrStatus:  input.Body.TldrStatus,
	}
	if err := h.DB.WithContext(ctx).Create(&row).Error; err != nil {
		return nil, database.MapPersistError(ctx, err, "resource already exists", "create release")
	}
	return &createReleaseOutput{
		Body: contract.Data[releaseData]{Data: toReleaseData(row)},
	}, nil
}

func toReleaseData(row Release) releaseData {
	return releaseData{ID: row.ID, Tag: row.Tag, Name: row.Name, Body: row.Body, Url: row.Url, PublishedAt: row.PublishedAt, Tldr: row.Tldr, TldrStatus: row.TldrStatus}
}
