// Code generated by gombit make resource. DO NOT EDIT.
package release

import "gorm.io/gorm"

// Release is the feature-package GORM model.
type Release struct {
	gorm.Model
	Tag         string `gorm:"size:255;not null;uniqueIndex"`
	Name        string `gorm:"size:255"`
	Body        string `gorm:"type:text"`
	Url         string `gorm:"size:255"`
	PublishedAt string `gorm:"size:255"`
	Tldr        string `gorm:"type:text"`
	TldrStatus  string `gorm:"size:255"`
}
