// Code generated by gombit make resource. DO NOT EDIT.
package release

import (
	"net/http"

	"github.com/danielgtaylor/huma/v2"
	"github.com/gombit-dev/gombit/framework"
)

// Register mounts release Huma routes. Called explicitly from main; Gombit
// does not discover feature packages by reflection.
func Register(app *framework.App) {
	h := &Handler{DB: app.DB()}
	prefix := app.Config().API.Prefix
	api := app.API()

	huma.Register(api, huma.Operation{
		OperationID: "list-releases",
		Method:      http.MethodGet,
		Path:        prefix + "/releases",
		Summary:     "List releases",
		Tags:        []string{"Releases"},
	}, h.list)

	huma.Register(api, huma.Operation{
		OperationID: "get-release",
		Method:      http.MethodGet,
		Path:        prefix + "/releases/{id}",
		Summary:     "Get a release",
		Tags:        []string{"Releases"},
	}, h.get)

	huma.Register(api, huma.Operation{
		OperationID: "create-release",
		Method:      http.MethodPost,
		Path:        prefix + "/releases",
		Summary:     "Create a release",
		Tags:        []string{"Releases"},
	}, h.create)
}
