/**
 * Code generated by gombit make resource. DO NOT EDIT.
 */

import { useState } from "react";
import { useForm } from "react-hook-form";
import { Link, useNavigate } from "react-router";

import { useApiClient } from "../api/client";
import { applyContractErrors } from "../api/formErrors";
import { unwrap } from "../api/generated/client";
import type { paths } from "../api/generated/schema";

const createPath = "/api/v1/releases" as const;

type CreateBody =
  paths[typeof createPath]["post"]["requestBody"]["content"]["application/json"];

type FormValues = {
  tag: string;
  name: string;
  body: string;
  url: string;
  published_at: string;
  tldr: string;
  tldr_status: string;
};

/**
 * React Hook Form create page. Request/response types come from the
 * generated OpenAPI client. D10 error.fields map through applyContractErrors.
 * Run gombit client generate or gombit dev after adding routes.
 */
export function ReleaseFormPage() {
  const client = useApiClient();
  const navigate = useNavigate();
  const [status, setStatus] = useState("");
  const {
    register,
    handleSubmit,
    setError,
    formState: { errors, isSubmitting },
  } = useForm<FormValues>({
    defaultValues: { tag: "", name: "", body: "", url: "", published_at: "", tldr: "", tldr_status: "" },
  });

  async function onSubmit(values: FormValues) {
    setStatus("");
    try {
      await unwrap(await client.POST(createPath, { body: values as CreateBody }));
      navigate("/releases");
    } catch (err: unknown) {
      if (!applyContractErrors(setError, err)) {
        setStatus(err instanceof Error ? err.message : "request failed");
      }
    }
  }

  return (
    <section>
      <h1>New Release</h1>
      <p>
        <Link to="/releases">Back to list</Link>
      </p>
      <form onSubmit={handleSubmit(onSubmit)}>
        <label>
          Tag
          <input type="text" {...register("tag", { required: "Tag is required" })} />
        </label>
        {errors.tag?.message ? <p>{errors.tag.message}</p> : null}
        <label>
          Name
          <input type="text" {...register("name")} />
        </label>
        {errors.name?.message ? <p>{errors.name.message}</p> : null}
        <label>
          Body
          <textarea {...register("body")} />
        </label>
        {errors.body?.message ? <p>{errors.body.message}</p> : null}
        <label>
          Url
          <input type="text" {...register("url")} />
        </label>
        {errors.url?.message ? <p>{errors.url.message}</p> : null}
        <label>
          PublishedAt
          <input type="text" {...register("published_at")} />
        </label>
        {errors.published_at?.message ? <p>{errors.published_at.message}</p> : null}
        <label>
          Tldr
          <textarea {...register("tldr")} />
        </label>
        {errors.tldr?.message ? <p>{errors.tldr.message}</p> : null}
        <label>
          TldrStatus
          <input type="text" {...register("tldr_status")} />
        </label>
        {errors.tldr_status?.message ? <p>{errors.tldr_status.message}</p> : null}
        <button type="submit" disabled={isSubmitting}>
          Create
        </button>
      </form>
      {status ? <p>{status}</p> : null}
    </section>
  );
}
