/**
 * Code generated by gombit make resource. DO NOT EDIT.
 *
 * Registry of resources created by `gombit make resource`. Re-run that
 * command to refresh this file. Pages import the generated OpenAPI client
 * from ./api/generated — run `gombit client generate` or `gombit dev`
 * after the API is up. Access tokens stay in memory.
 */

import type { RouteObject } from "react-router";

export type GeneratedResource = {
  slug: string;
  title: string;
  listPath: string;
  createPath: string;
};

export const generatedResources: GeneratedResource[] = [];

export const generatedResourceRoutes: RouteObject[] = [];
