/**
 * Code generated by gombit make resource. DO NOT EDIT.
 */

// React list + create-form pages. Types come from ./api/generated
// (gombit client generate / gombit dev). OpenAPI path keys use /api/v1;
// createAppClient rewrites them to the live GOMBIT_API_PREFIX.
// Access tokens stay in memory; this file does not use web storage.

import type { RouteObject } from "react-router";

import { ReleaseListPage } from "./release/list";
import { ReleaseFormPage } from "./release/form";

export type GeneratedResource = {
  slug: string;
  title: string;
  listPath: string;
  createPath: string;
};

export const generatedResources: GeneratedResource[] = [
  {
    slug: "release",
    title: "Release",
    listPath: "/releases",
    createPath: "/releases/new",
  },
];

export const generatedResourceRoutes: RouteObject[] = [
  { path: "releases", element: <ReleaseListPage /> },
  { path: "releases/new", element: <ReleaseFormPage /> },
];
